import cv2
import numpy as np

def video_to_array(path):
    video = cv2.VideoCapture(path)
    frames = []

    while True:
        ret, frame = video.read()
        if not ret:
            break

        frame = cv2.resize(frame, (18,18)) 
        frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        _, frame_binary = cv2.threshold(frame_gray, 128, 255, cv2.THRESH_BINARY)
        frames.append((frame_binary // 255).tolist())

    video.release()
    return frames

result = video_to_array('badapple.mp4')

with open("badapple.js", "w") as f:
    f.write("//THIS FILE WAS AUTOMATICALLY GENERATED BY badapple.py\nconst BADAPPLE = "+str(result).replace(" ","")+";\nexport { BADAPPLE };")
