import cv2
import numpy as np

size = (16, 10)  # width, height

def video_to_array(path):
    video = cv2.VideoCapture(path)
    frames = []

    while True:
        ret, frame = video.read()
        if not ret:
            break

        frame = cv2.resize(frame, size)
        frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        _, frame_binary = cv2.threshold(frame_gray, 128, 255, cv2.THRESH_BINARY)

        expanded_frame = []
        for i in range(0, size[1]):  # Проход по высоте кадра
            row = []
            for j in range(0, size[0]):  # Проход по ширине кадра
                top_left = frame_binary[i, j]
                top_right = frame_binary[i, (j + 1) % size[0]]
                bottom_left = frame_binary[(i + 1) % size[1], j]
                bottom_right = frame_binary[(i + 1) % size[1], (j + 1) % size[0]]
                element = f"{top_left // 255}{top_right // 255}{bottom_left // 255}{bottom_right // 255}"
                row.append(element)
            expanded_frame.append(row)
        
        frames.append(expanded_frame)

    video.release()
    return frames

result = video_to_array('video.mp4')

with open("generated.js", "w") as f:
    f.write("//THIS FILE WAS AUTOMATICALLY GENERATED BY convert.py\nconst GENERATED = "+str(result).replace(" ","")+";\nmodule.exports = { GENERATED };")
