import cv2
import numpy as np

#TODO:  the difference between the start and end coordinates
size = (32,32)

def video_to_array(path):
    video = cv2.VideoCapture(path)
    frames = []

    while True:
        ret, frame = video.read()
        if not ret:
            break

        frame = cv2.resize(frame, size) 
        frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        _, frame_binary = cv2.threshold(frame_gray, 128, 255, cv2.THRESH_BINARY)
        frames.append((frame_binary // 255).tolist())

    video.release()
    return frames

result = video_to_array('video.mp4')

with open("generated.js", "w") as f:
    f.write("//THIS FILE WAS AUTOMATICALLY GENERATED BY convert.py\nconst GENERATED = "+str(result).replace(" ","")+";\nmodule.exports = { GENERATED };")
